### PR TITLE
Add JIRA ID in doc string of each test function

### PR DESCRIPTION
**Pull request by flei2000**
Add JIRA ID into doc string of each test function
Add dummy test cases in bucket test.
Rename bucket_test.py to bucket_create_delete.py

### CODE REVIEW

**Comment by smw** [comment]
Just out of curiosity, what's the point of JIRA IDs?

**Comment by flei2000** [comment]
Ming Zhang [ISE] [10:13 AM] 
Back track to where we have the spec.
Lei Feng:
I agree that JIRA ID is not readable. But at least it is an option not to lose the track before we find a better way.

**Comment by stevendgonzales** [comment]
I don't think we should change the Python module to match the single TestCase class.  I think many bucket related TestCase classes can fit in the same module.  In Python there is not a tight relationship between a single class and the file as in Java.  The module is more of a namespace.  If we have 2000 tests that will make for a lot of modules.

**Comment by stevendgonzales** [comment]
I probably should have named the user_login_test.py something like authentication_test.py so it can hold all auth related test cases, including testing logging out as well

**Comment by flei2000** [comment]
So you like bucket_test.py more than bucket_create_delete.py?

**Comment by stevendgonzales** [comment]
Yes I do, because it represents a namespace that can hold a larger number of bucket related testcases.  I think my original example of user_login_test.py was too narrow

**Pull request merged**
